# This playbook setup a machine for building aports. 
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install alpine-sdk package
  command: /sbin/apk add alpine-sdk
